version: '3'

services:
  nginx-proxy-manager:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt

  adguard-home:
    image: adguard/adguardhome:latest
    restart: unless-stopped
    ports:
      - 53:53/udp
      - 67:67/udp 
      - 68:68/tcp 
      - 68:68/udp 
      - 80:80/tcp 
      - 443:443/tcp 
      - 853:853/tcp 
      - 3000:3000/tcp
      - 3030:3030/tcp
    volumes:
      - ./data/adguardhome/work:/opt/adguardhome/work
      - ./data/adguardhome/conf:/opt/adguardhome/conf
      - ./data/adguardhome/logs:/opt/adguardhome/logs
